version: '3.8'
services:
  transdb:
    image: postgres:13
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - transnet
    volumes:
      - devdb:/var/lib/postgresql/data
networks:
  transnet:

volumes:
  devdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/data/devdb
